<a href="https://colab.research.google.com/github/ameliaziolkowski/Data_Sci/blob/main/AmeliaZiolkowski_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(5,8):
    print(3)

3
3
3


In [ ]:
for i in range(5,8):                                                            #does not include the last number
    print(i)

5
6
7


In [ ]:
for i in range(3):
    print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


In [ ]:
for i in range(5):
    print("Oranges: ",2)

Oranges:  2
Oranges:  2
Oranges:  2
Oranges:  2
Oranges:  2


In [ ]:
for i in range(10):
    print("Statistics: ",i)

Statistics:  0
Statistics:  1
Statistics:  2
Statistics:  3
Statistics:  4
Statistics:  5
Statistics:  6
Statistics:  7
Statistics:  8
Statistics:  9


In [ ]:
for i in range(7):
    print("green ",i)

green  0
green  1
green  2
green  3
green  4
green  5
green  6


In [ ]:
def square(x):                                                                  #functions start with def space
    return x**2

In [ ]:
square(5)

25

In [ ]:
square(13)


169

In [ ]:
square(square(2))

16

In [ ]:
def cubed(x):
    return x**3

In [ ]:
cubed(3)

27

In [ ]:
cubed(13)

2197

In [ ]:
def add_two(x):
    return x+2

In [ ]:
add_two(5)

7

In [ ]:
square(add_two(5))

49

In [ ]:
square(add_two(8))

100

In [ ]:
choice = "apple"                                   #one equal sign is assignment and two equal signs a test


In [ ]:
if choice == "apple":
    print("You choose apples.")
else:
    print("You did not choose apples.")

You choose apples.


In [ ]:
choice = "orange"

In [ ]:
if choice == "apple":
    print("You choose apples.")
elif choice == "orange":
    print("You choose oranges.")
else:
    print("You did not choose apples or oranges")

You choose oranges.


In [ ]:
if choice == "apple":
    print("You choose apples.")
elif choice == "orange":
    print("You choose oranges.")
else:
    print("You did not choose apples or oranges")

You choose oranges.


In [ ]:
if choice == "apple":
    print("You choose apples.")
    print("Thank you, shop again!")

elif choice == "orange":
    print("You choose oranges.")
    print("Hello")    
else:
    print("You did not choose apples or oranges")

You choose oranges.
Hello


In [ ]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): j


In [ ]:
choice

'j'

In [ ]:
choice

'j'

In [ ]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): n


In [ ]:
choice

'n'

### permutations

In [ ]:
import numpy as np


In [ ]:
np.random.permutation(52)

array([23,  3, 47,  1, 18,  4, 40, 39, 42, 43,  7, 14, 50, 19, 17, 30, 26,
        5, 15, 31, 46, 49, 45, 24, 37, 22, 38, 21,  6, 16,  2, 28, 44,  9,
       11, 51, 34, 10, 27,  0, 36, 12, 41,  8, 20, 33, 13, 29, 25, 35, 32,
       48])

In [ ]:
cards = np.random.permutation(52)

In [ ]:
cards

array([32, 27, 35,  2, 29, 43, 24, 19, 16, 46, 38, 20,  4, 26,  3, 31, 33,
       42, 11,  7, 41, 15, 10, 36, 13,  5, 25,  0,  9, 47, 18, 49, 51, 40,
       21, 22, 28,  8, 50, 37, 34, 39, 45, 23, 48, 30, 12, 44,  1,  6, 17,
       14])

In [ ]:
cards[0]

32

In [ ]:
cards[1]

27

In [ ]:
cards[3]

2

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [ ]:
suits[0]

'Clubs'

In [ ]:
def card_name(card_number):
    suit = card_number//13
    name = card_number%13
    return names[name] + " of " + suits[suit]


In [ ]:
card_name(0)

'Ace of Clubs'

In [ ]:
card_name(6)


'Seven of Clubs'

In [ ]:
card_name(13)

'Ace of Spades'

In [ ]:
cards = np.random.permutation(52)

In [ ]:
top_of_deck = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck = card_name(cards[-1])

In [ ]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Ten of Clubs', 'Nine of Clubs', 'Seven of Clubs')

In [ ]:
for i in range(5):
    print(card_name(cards[i]))

Ten of Clubs
Nine of Clubs
Six of Diamonds
Six of Spades
Jack of Hearts


In [ ]:
for i in range(10):
    print(card_name(cards[i]))                                                  #assigns each card a name

Ten of Clubs
Nine of Clubs
Six of Diamonds
Six of Spades
Jack of Hearts
Ace of Clubs
Three of Spades
Seven of Spades
Eight of Spades
Ace of Diamonds


In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [ ]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [ ]:
i = np.random.randint(4)
j = np.random.randint(13)

In [ ]:
i,j

(0, 7)

In [ ]:
suit[i]


'k'

In [ ]:
card[j]

'8'

In [ ]:
card[j]

'8'

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [ ]:
show_img(img)

In [ ]:
img = card_url_head + suit[i] + card[2] + card_url_tail

In [ ]:
show_img(img)

In [ ]:
img = card_url_head + suit[i] + card[11] + card_url_tail

In [ ]:
show_img(img)