<a href="https://colab.research.google.com/github/ameliaziolkowski/Data_Sci/blob/main/Ziolkowski_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [2]:
for i in range(5,8):
    print(3)

3
3
3


In [3]:
for i in range(5,8):                                                            #does not include the last number
    print(i)

5
6
7


In [4]:
for i in range(3):
    print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


In [5]:
for i in range(5):
    print("Oranges: ",2)

Oranges:  2
Oranges:  2
Oranges:  2
Oranges:  2
Oranges:  2


In [6]:
for i in range(10):
    print("Statistics: ",i)

Statistics:  0
Statistics:  1
Statistics:  2
Statistics:  3
Statistics:  4
Statistics:  5
Statistics:  6
Statistics:  7
Statistics:  8
Statistics:  9


In [7]:
for i in range(7):
    print("green ",i)

green  0
green  1
green  2
green  3
green  4
green  5
green  6


In [8]:
def square(x):                                                                  #functions start with def space
    return x**2

In [9]:
square(5)

25

In [10]:
square(13)


169

In [11]:
square(square(2))

16

In [12]:
def cubed(x):
    return x**3

In [13]:
cubed(3)

27

In [14]:
cubed(13)

2197

In [15]:
def add_two(x):
    return x+2

In [16]:
add_two(5)

7

In [17]:
square(add_two(5))

49

In [18]:
square(add_two(8))

100

In [19]:
choice = "apple"                                   #one equal sign is assignment and two equal signs a test


In [20]:
if choice == "apple":
    print("You choose apples.")
else:
    print("You did not choose apples.")

You choose apples.


In [25]:
choice = "orange"

In [26]:
if choice == "apple":
    print("You choose apples.")
elif choice == "orange":
    print("You choose oranges.")
else:
    print("You did not choose apples or oranges")

You choose oranges.


In [27]:
if choice == "apple":
    print("You choose apples.")
elif choice == "orange":
    print("You choose oranges.")
else:
    print("You did not choose apples or oranges")

You choose oranges.


In [28]:
if choice == "apple":
    print("You choose apples.")
    print("Thank you, shop again!")

elif choice == "orange":
    print("You choose oranges.")
    print("Hello")    
else:
    print("You did not choose apples or oranges")

You choose oranges.
Hello


In [30]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): pear


In [31]:
choice

'pear'

In [32]:
choice

'pear'

In [33]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): statistics


In [34]:
choice

'statistics'

### permutations

In [39]:
import numpy as np


In [41]:
np.random.permutation(52)

array([15,  5, 44, 25,  6, 34, 51, 12, 14, 31, 11, 16, 17, 49, 35, 30, 10,
       18,  7, 46,  1, 37,  4,  9, 42, 40, 13, 36, 23, 48, 41, 32,  2, 39,
       28, 29,  0, 24, 26,  3, 47, 22, 38, 33,  8, 19, 50, 45, 20, 27, 21,
       43])

In [43]:
cards = np.random.permutation(52)

In [44]:
cards

array([11,  9,  0, 46, 21, 39, 26, 15, 24, 34, 44, 17,  4, 31, 37,  6, 12,
       48,  5, 22, 50, 25, 23, 43,  3, 45, 13, 38, 35, 42, 16, 51, 49, 27,
       14,  2, 18, 40, 33, 47, 30, 32, 28,  7, 10, 36, 41, 20,  1, 29,  8,
       19])

In [45]:
cards[0]

11

In [46]:
cards[1]

9

In [47]:
cards[3]

46

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [48]:
np.arange(52).reshape(4,13)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [49]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [50]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [51]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [52]:
suits[0]

'Clubs'

In [60]:
def card_name(card_number):
    suit = card_number//13
    name = card_number%13
    return names[name] + " of " + suits[suit]


In [61]:
card_name(0)

'Ace of Clubs'

In [62]:
card_name(6)


'Seven of Clubs'

In [63]:
card_name(13)

'Ace of Spades'

In [64]:
cards = np.random.permutation(52)

In [65]:
top_of_deck = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck = card_name(cards[-1])

In [66]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Two of Spades', 'Two of Hearts', 'Nine of Hearts')

In [67]:
for i in range(5):
    print(card_name(cards[i]))

Two of Spades
Two of Hearts
King of Clubs
King of Diamonds
Seven of Hearts


In [68]:
for i in range(10):
    print(card_name(cards[i]))

Two of Spades
Two of Hearts
King of Clubs
King of Diamonds
Seven of Hearts
Queen of Diamonds
Ten of Clubs
Nine of Spades
Six of Hearts
Jack of Hearts


In [69]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [70]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [71]:
i = np.random.randint(4)
j = np.random.randint(13)

In [72]:
i,j

(2, 1)

In [73]:
suit[i]


's'

In [74]:
card[j]

'2'

In [75]:
card[j]

'2'

In [78]:
from IPython.core.display import display, HTML

In [79]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [81]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [82]:
show_img(img)